"""empty message

Revision ID: 225f8156e7bd
Revises: 190418425df2
Create Date: 2023-06-07 15:36:37.945561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225f8156e7bd'
down_revision = '190418425df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('films',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('films',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
