"""empty message

Revision ID: da678c47244a
Revises: 
Create Date: 2023-05-29 18:26:46.368398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da678c47244a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id_character', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('bith_year', sa.String(length=250), nullable=False),
    sa.Column('eye_color', sa.String(length=250), nullable=True),
    sa.Column('gender', sa.String(length=250), nullable=True),
    sa.Column('hair_color', sa.String(length=250), nullable=True),
    sa.Column('mass', sa.String(length=250), nullable=False),
    sa.Column('skin_color', sa.String(length=250), nullable=False),
    sa.Column('species', sa.String(length=250), nullable=False),
    sa.Column('starship', sa.String(length=250), nullable=False),
    sa.Column('films', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_character'),
    sa.UniqueConstraint('id_character'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planet',
    sa.Column('id_planet', sa.Integer(), nullable=False),
    sa.Column('climate', sa.String(length=250), nullable=False),
    sa.Column('films', sa.Integer(), nullable=False),
    sa.Column('gravity', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('orbital_period', sa.String(length=250), nullable=False),
    sa.Column('population', sa.String(length=250), nullable=False),
    sa.Column('residents', sa.String(length=250), nullable=False),
    sa.Column('rotation_period', sa.String(length=250), nullable=False),
    sa.Column('surface_water', sa.String(length=250), nullable=False),
    sa.Column('terrain', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_planet', 'films'),
    sa.UniqueConstraint('id_planet')
    )
    op.create_table('starship',
    sa.Column('id_starship', sa.Integer(), nullable=False),
    sa.Column('cargo_capacity', sa.Integer(), nullable=False),
    sa.Column('consumable', sa.String(length=250), nullable=False),
    sa.Column('cost_in_credits', sa.Integer(), nullable=False),
    sa.Column('crew', sa.String(length=250), nullable=False),
    sa.Column('hyperdrive_rating', sa.Integer(), nullable=False),
    sa.Column('mglt', sa.String(length=250), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=250), nullable=False),
    sa.Column('max_atmosfering_speed', sa.String(length=250), nullable=False),
    sa.Column('model', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('films', sa.String(length=250), nullable=False),
    sa.Column('pilots', sa.String(length=250), nullable=False),
    sa.Column('starship_class', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_starship'),
    sa.UniqueConstraint('id_starship')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_user')
    )
    op.create_table('cha__favs',
    sa.Column('id_cha_favs', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_cha_favs'),
    sa.UniqueConstraint('id_cha_favs')
    )
    op.create_table('film',
    sa.Column('id_films', sa.Integer(), nullable=False),
    sa.Column('film_name', sa.String(length=250), nullable=False),
    sa.Column('characters', sa.Integer(), nullable=False),
    sa.Column('starships', sa.Integer(), nullable=False),
    sa.Column('planets', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['characters'], ['character.id_character'], ),
    sa.ForeignKeyConstraint(['planets'], ['planet.id_planet'], ),
    sa.ForeignKeyConstraint(['starships'], ['starship.id_starship'], ),
    sa.PrimaryKeyConstraint('id_films'),
    sa.UniqueConstraint('id_films')
    )
    op.create_table('pla__favs',
    sa.Column('id_pla_favs', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_pla_favs'),
    sa.UniqueConstraint('id_pla_favs')
    )
    op.create_table('shi__favs',
    sa.Column('id_shi_favs', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_shi_favs'),
    sa.UniqueConstraint('id_shi_favs')
    )
    op.create_table('collaboration',
    sa.Column('id_collab', sa.Integer(), nullable=False),
    sa.Column('id_films', sa.Integer(), nullable=False),
    sa.Column('id_characters', sa.Integer(), nullable=False),
    sa.Column('id_starships', sa.Integer(), nullable=False),
    sa.Column('id_planets', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_characters'], ['character.id_character'], ),
    sa.ForeignKeyConstraint(['id_films'], ['film.id_films'], ),
    sa.ForeignKeyConstraint(['id_planets'], ['planet.id_planet'], ),
    sa.ForeignKeyConstraint(['id_starships'], ['starship.id_starship'], ),
    sa.PrimaryKeyConstraint('id_collab'),
    sa.UniqueConstraint('id_collab')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collaboration')
    op.drop_table('shi__favs')
    op.drop_table('pla__favs')
    op.drop_table('film')
    op.drop_table('cha__favs')
    op.drop_table('user')
    op.drop_table('starship')
    op.drop_table('planet')
    op.drop_table('character')
    # ### end Alembic commands ###
