"""empty message

Revision ID: ec17f8ff988c
Revises: 
Create Date: 2023-06-02 18:49:28.622560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec17f8ff988c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('birth_year', sa.String(length=250), nullable=False),
    sa.Column('eye_color', sa.String(length=250), nullable=True),
    sa.Column('gender', sa.String(length=250), nullable=True),
    sa.Column('hair_color', sa.String(length=250), nullable=True),
    sa.Column('mass', sa.String(length=250), nullable=False),
    sa.Column('skin_color', sa.String(length=250), nullable=False),
    sa.Column('species', sa.String(length=250), nullable=False),
    sa.Column('starship', sa.String(length=250), nullable=False),
    sa.Column('films', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('climate', sa.String(length=250), nullable=False),
    sa.Column('films', sa.Integer(), nullable=False),
    sa.Column('gravity', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('orbital_period', sa.String(length=250), nullable=False),
    sa.Column('population', sa.String(length=250), nullable=False),
    sa.Column('residents', sa.String(length=250), nullable=False),
    sa.Column('rotation_period', sa.String(length=250), nullable=False),
    sa.Column('surface_water', sa.String(length=250), nullable=False),
    sa.Column('terrain', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id', 'films'),
    sa.UniqueConstraint('id')
    )
    op.create_table('starship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_capacity', sa.Integer(), nullable=False),
    sa.Column('consumable', sa.String(length=250), nullable=False),
    sa.Column('cost_in_credits', sa.Integer(), nullable=False),
    sa.Column('crew', sa.String(length=250), nullable=False),
    sa.Column('hyperdrive_rating', sa.Integer(), nullable=False),
    sa.Column('mglt', sa.String(length=250), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=250), nullable=False),
    sa.Column('max_atmosfering_speed', sa.String(length=250), nullable=False),
    sa.Column('model', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('films', sa.String(length=250), nullable=False),
    sa.Column('pilots', sa.String(length=250), nullable=False),
    sa.Column('starship_class', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('cha__favs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cha_favs', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cha_favs'], ['character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('film_name', sa.String(length=250), nullable=False),
    sa.Column('characters', sa.Integer(), nullable=False),
    sa.Column('starships', sa.Integer(), nullable=False),
    sa.Column('planets', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['characters'], ['character.id'], ),
    sa.ForeignKeyConstraint(['planets'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['starships'], ['starship.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('pla__favs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pla_favs', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pla_favs'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('shi__favs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_shi_favs', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_shi_favs'], ['starship.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('collaboration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_films', sa.Integer(), nullable=False),
    sa.Column('characters', sa.Integer(), nullable=False),
    sa.Column('id_starships', sa.Integer(), nullable=False),
    sa.Column('id_planets', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['characters'], ['character.id'], ),
    sa.ForeignKeyConstraint(['id_films'], ['film.id'], ),
    sa.ForeignKeyConstraint(['id_planets'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['id_starships'], ['starship.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collaboration')
    op.drop_table('shi__favs')
    op.drop_table('pla__favs')
    op.drop_table('film')
    op.drop_table('cha__favs')
    op.drop_table('user')
    op.drop_table('starship')
    op.drop_table('planet')
    op.drop_table('character')
    # ### end Alembic commands ###
